services:
  - type: web
    name: casamance-culture
    env: docker
    plan: free
    dockerfilePath: .Dockerfile
    autoDeploy: false
    disk:
      name: ghost-content
      mountPath: /var/lib/ghost/content
      sizeGB: 1
